[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Devant", "Chunkers", "Vendor/WSO2", "Area/AI", "Type/Util"]
license = ["Apache-2.0"]
name = "ai.devant"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.devant"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true
