[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Devant", "Chunkers"]
license = ["Apache-2.0"]
name = "ai.devant"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.devant"
version = "1.0.2"

[platform.java21]
graalvmCompatible = true
